#!/bin/sh

###################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004. See
# http://www.eu-egee.org/partners/ for details on the copyright holders.
# 
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#
###################################################################

# Unfortunately the localinit target runs _after_ the init-autotools target,
# so we cannot do this from ant

# version=`grep ^module.version project/version.properties | cut -d= -f2 | sed -e 's/[         ]//g'`
version=`grep ^VERSION VERSION | cut -d= -f2 | sed -e 's/[         ]//g'`
echo "Version = $version"
echo "AC_DEFUN([GLITE_MODULE_VERSION],[$version])" > project/module-version.m4

interface_version=2.0.0
m4_macros_location=/usr/share/fts/aclocal/
stageDir=""
prefix=""
metadata_interface_version="2.0.0"

cp ${m4_macros_location}/glite.m4 ${m4_macros_location}/gsoap.m4 ${m4_macros_location}/glite-version.m4 ${m4_macros_location}/cgsi-gsoap.m4 ./project;

mkdir -p src/autogen
set -x
aclocal -I project
libtoolize --force
autoheader
automake --foreign --add-missing --copy
autoconf

